### PR TITLE
feat: Set Default theme as Dark and add toggle button

### PR DESCRIPTION
**Pull request by Asin-Junior-Honore**
## Title
 feat: Set Default theme as Dark and add toggle button

## Related Issue(s)
 This pull request addresses the issue related to setting the default theme as dark and adding a toggle button for theme switching. #143 

## Additional Info
The ThemeProvider has been updated to set the default theme as dark and provide a toggle button in the UI for users to switch between themes. This enhancement improves user experience by allowing them to choose their preferred theme.

## Screenshots
 
makautt-herosection

### CODE REVIEW

**Comment by Arindam200** [comment]
@Asin-Junior-Honore  Can you Please Fix Few things? 

- We don't need any Light mode. You can remove that toggle button
- Overall section theme is not changing, Only a few parts of that. 

We want and uniform deafult Dark theme. 

For example these sections haven't changed: 
- image
- 
image

**Comment by Asin-Junior-Honore** [comment]
@Arindam200
ok now am confused on what to do you mean they  shouldn't be able to toggle between light and darkmode?
please can you make the request more brief and detailed please 🙏

**Comment by Arindam200** [comment]
@Asin-Junior-Honore Sorry for the Confusion.

We want only the Dark theme, No light theme is needed (as the UI doesn't look good in light mode) 

So We want if the User's default theme is light then also he/she should see the default dark theme for this Project. 

Otherwise in light mode the project looks like this: 
image

Where as we want that to be like this in light mode: 
image

let me know if you have any other doubts

**Comment by Asin-Junior-Honore** [comment]
@Arindam200,

I have made some adjustments as you requested. Please take a look at the color combination I used below and let me know if I can push and commit these changes, or if further adjustments are needed. Thank you! 🥲

Screenshot (18)
----
Screenshot (19)

----
Screenshot (20)
---

Screenshot (21)
---

Screenshot (22)

**Comment by Arindam200** [comment]
Hey @Asin-Junior-Honore 

Please make everything the background black (what we have currently in the dark mode)

**Comment by Arindam200** [comment]
@Asin-Junior-Honore 
All the Pages in Light mode should look like this: 

image
image
image
image

**Comment by Asin-Junior-Honore** [comment]
@Arindam200 all done sir🙌

**Review by Arindam200 — APPROVED** [review]
LGTM!

Awesome Work!

**Comment by Arindam200** [comment]
Great Work @Asin-Junior-Honore ! Thanks a lot for the great contribution!

Feel Free to Contribute more.

**Pull request merged**
