### PR TITLE
Fix: dropdown in faq section

### PR DESCRIPTION
**Pull request by nikhilgarg26**
## Title
Dropdowns in the FAQ section

## Related Issue(s)
#24 

## Additional Info
Added some css to the FAQ text `<div>`

https://github.com/Arindam200/makaut_buddy/assets/116938919/ee0ad9db-6a91-41c4-82d8-984edb1ec49f

### Summary by CodeRabbit

**Style:**
- Adjusted the positioning and padding of the FAQ component for better alignment and spacing. This includes changes to the height of certain elements for a more balanced layout.
- Updated the Navbar component with an improved link behavior to prevent unnecessary page scrolling.

**Chore:**
- Extended the Tailwind CSS configuration with new height properties, providing more flexibility in component styling. 

Please note that these changes are primarily visual and do not affect the functionality of the components.

### CODE REVIEW

**Comment by nikhilgarg26** [comment]
i made a new branch this issue and the commit of previous issue i resolved is also reflected in it should i delete the `href="#"` from this commit

**Comment by nikhilgarg26** [comment]
@Arindam200 please review it

**Review by Swpn0neel — COMMENTED** [review]
Already resolved, hence redundant

**Review by Swpn0neel — COMMENTED** [review]
Please remove unnecessary padding, it's creating extra blank spaces.

**Comment by nikhilgarg26** [comment]
> Please remove unnecessary padding, it's creating extra blank spaces.

please make it clear which paddings and what changes need to be made

**Comment by Arindam200** [comment]
Hey @nikhilgarg26 we wanted Only the right-side questions (drop-downs) section should move and respond to the animation. That means the height of the FAQ section should be constant.

**Comment by nikhilgarg26** [comment]
> Hey @nikhilgarg26 we wanted Only the right-side questions (drop-downs) section should move and respond to the animation. That means the height of the FAQ section should be constant.


https://github.com/Arindam200/makaut_buddy/assets/116938919/06767a4a-b2d5-4d73-8cbf-a6f0af68b440

is this correct @Arindam200 then i would create a pr

**Comment by nikhilgarg26** [comment]
i have made the changes please review it @Arindam200

**Review by Swpn0neel — APPROVED** [review]
LGTM

**Review by Swpn0neel — APPROVED** [review]

**Comment by Swpn0neel** [comment]
Kindly check the deployment @Arindam200 and merge the PR 👍

**Comment by Arindam200** [comment]
Hey, @nikhilgarg26 ! Great Work! 

It's working for Large screens. Can you fix that for the small screens ??

**Comment by nikhilgarg26** [comment]
> [Swpn0neel](/Swpn0neel)
> ** [Swpn0neel](/Swpn0neel) ** approved these changes

i guess for that we need to make the footer moving up down with the right side animation and we can fix the position of FAQ left side

**Comment by nikhilgarg26** [comment]
> Hey, @nikhilgarg26 ! Great Work!
> 
> It's working for Large screens. Can you fix that for the small screens ??

i guess for that we need to make the footer moving up down with the right side animation and we can fix the position of FAQ left side

**Comment by Swpn0neel** [comment]
> > Hey, @nikhilgarg26 ! Great Work!
> > It's working for Large screens. Can you fix that for the small screens ??
> 
> i guess for that we need to make the footer moving up down with the right side animation and we can fix the position of FAQ left side

No, you just have to give the height of that section in 'rem'/ Tailwind CSS's default unit.. not in px.

**Review by Swpn0neel — CHANGES_REQUESTED** [review]
You have to use rem/em units for the responsiveness in both mobile/desktop devices, you can do that by using properties like 'h-32;, now try tinkering with that until you get the desired height!!

**Comment by nikhilgarg26** [comment]
please check

**Review by Arindam200 — APPROVED** [review]

**Comment by Swpn0neel** [comment]
Resolve @nikhilgarg26 

image

**Review by Swpn0neel — CHANGES_REQUESTED** [review]
Just check it carefully and fix it.

**Pull request closed without merging**
