### PR TITLE
(fix): The Alignment of two Assets #18

### PR DESCRIPTION
**Pull request by mehulrnsit**
image

### Summary by CodeRabbit

- Style: Adjusted the visual layout of the `Features` component. The image size has been modified and repositioned for better alignment.
- Style: Updated the `Hero` component's image positioning with a new top margin, enhancing the overall aesthetic appeal of the page.

### CODE REVIEW

**Comment by Arindam200** [comment]
Hey @mehulrnsit ! The Design we want is like this : 
image

Can you please Fix that?

**Comment by mehulrnsit** [comment]
Is this okay?
image

**Comment by Arindam200** [comment]
Yes! Absolutely!

**Comment by mehulrnsit** [comment]
Added a new commit :)

**Review by Swpn0neel — APPROVED** [review]

**Pull request merged**
