### PR TITLE
[Feat:] Added back button functionality in dashboard section and made it responsive

### PR DESCRIPTION
**Pull request by RitochitGhosh**
## Description
Users should be provided a back-to-home page functionality from the Dashboard section for a better user experience. Added that feature  into the dashboard section and made it responsive for small screen devices.

### Method Adopted:
- Modified the src/app/dashboard/page.jsx file.
- Used a Link to direct from the Dashboard page to the Home page.
- Used "ArrowBackIosNewRoundedIcon" from Material UI as a displaying Icon.
- Positioned it for both mobile and large-screen devices.
### Here is how it looks now:

- **For mobile devices**

Screenshot 2024-05-20 181349

- **For large Screen devices**

Screenshot 2024-05-20 190252

### CODE REVIEW

**Comment by Arindam200** [comment]
In Mobile design, Try to put the user profile in the top right corner.

Rest Looks Good.

**Review by Swpn0neel — CHANGES_REQUESTED** [review]
Implement the changes mentioned by @Arindam200 , and please don't use `absolute`, you can achieve the same by using padding, flex, `items-center` or `justify-center`

**Comment by RitochitGhosh** [comment]
Ok, I will keep the mentioned things in mind and will be implementing the required changes as mentioned by @Arindam200.

**Comment by RitochitGhosh** [comment]
Optimized the design and added the avatar in the top bar for mobile devices. Adjusted the size of the avatar for large-screen devices. Please let me know if any more changes are rquired.

**Pull request merged**
