### PR TITLE
Feature: loading sign for globe

### PR DESCRIPTION
**Pull request by GeorgiosDrivas**
##Title
(feat): Loading sign on globe

##Issue
#140 

## Additional Info
I have created a component called loadingSpinner in case there is a need for a loading sign in the future. There is a useState that checks whether the globe is rendered. If not, the loading sign is visible. When the globe is rendered, the sign will disappear.

The loading sign is animated.

## Screenshots
loading_screenshot

### CODE REVIEW

**Review by Arindam200 — APPROVED** [review]

**Comment by Arindam200** [comment]
Hey @GeorgiosDrivas , 

Instead of a loading spinner, can you please add a static image until the globe loads?

**Comment by GeorgiosDrivas** [comment]
@Arindam200 

Of course I will add a static image. Would you like to choose a specific one and send it to me? 
So we don't go back and forth until we find the right one.

**Comment by Arindam200** [comment]
Thanks, @GeorgiosDrivas  , Can you just take a static image of the current Globe? 

I don't have an image currently!

**Comment by GeorgiosDrivas** [comment]
@Arindam200 I have made some changes. I tried to place the static image as close to the position of the globe as possible in order to make it seem prettier. I kept the component I created ini case it needs to be placed somewhere else, but changed it's name to describe it's purpose better.

**Comment by Arindam200** [comment]
Hey @GeorgiosDrivas , 

We have fixed the Theme Issue. 

Can you please fix the Globe accordingly?

**Comment by GeorgiosDrivas** [comment]
@Arindam200, hello!

I saw the changes you made to the theme, they are very beautiful. 
I have adjusted the static image for the loading sign.

**Comment by GeorgiosDrivas** [comment]
@Arindam200 Hello,

Many days have passed since I made the changes based on the new theme. Is everything ok and ready to merge or do I need to make any additional changes?

**Comment by Arindam200** [comment]
Hey @GeorgiosDrivas ! 

Sorry for the late reply. Can you please remove the background of the circle?

And also there is a shift of the globe when it;s getting looaded. Most porbably the image is not aligned.

Can you please fix these?

**Pull request closed without merging**
