### PR TITLE
[Fix] : fixes dropdown faq section 

### PR DESCRIPTION
**Pull request by Rehan52004**
Dropdown FAQ Section fixed.

On clicking dropdown it effect other section like footer and left part of FAQ section.

fixes : #24 

https://github.com/Arindam200/makaut_buddy/assets/106008086/4fc0ee59-7654-46c7-a4ff-5d92af618b92

### Summary by CodeRabbit

- Refactor: Improved readability and maintainability of the FAQ component. The changes include reorganization of JSX code, renaming variables for clarity, and splitting content strings into multiple lines.
- Style: Updated class names and styles in the FAQ component to enhance UI consistency.
  
Please note that these changes do not introduce any new features or fix bugs, but they improve the code quality and may ease future development efforts.

### CODE REVIEW

**Comment by Rehan52004** [comment]
firstly i put wrong video demo, this the right video demo.


https://github.com/Arindam200/makaut_buddy/assets/106008086/654c72ad-0ec8-4632-b0de-81c2106d0f3d

**Review by Swpn0neel — CHANGES_REQUESTED** [review]
This is not acceptable.

Don't farm PRs by changing double quotes to single quotes and implementing unnecessary spaces.

You have a whole month for 4 PRs, make some healthy contributions please!!

Thank You.

**Comment by Rehan52004** [comment]
Really sorry for that, actually i am beginner in open source contribution.

**Comment by Arindam200** [comment]
I'm Closing this PR !

**Pull request closed without merging**
